name: CAPlayground
options:
  bundleIdPrefix: com.caplayground
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.caplayground.app
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: ""
    PROVISIONING_PROFILE_SPECIFIER: ""

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: "0.9.0"

targets:
  CAPlayground:
    type: application
    platform: iOS
    sources:
      - path: CAPlayground
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: CAPlayground/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.caplayground.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    dependencies:
      - package: ZIPFoundation
    info:
      path: CAPlayground/Info.plist
      properties:
        CFBundleDisplayName: CAPlayground
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
        UIStatusBarStyle: UIStatusBarStyleDefault
        ITSAppUsesNonExemptEncryption: false

  CAPlaygroundTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: CAPlayground
    settings:
      base:
        SWIFT_VERSION: "5.9"
